language: r
cache: packages
r_packages:
- knitr
- covr
notifications:
  slack: edmondsons:kgTokxui4ZzTsqdD19tCoozf
  email:
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'covr::codecov()'

