language: r
cache: packages
r_packages:
- knitr
- covr
notifications:
  slack: edmondsons:kgTokxui4ZzTsqdD19tCoozf
  email:
    on_success: change
    on_failure: change
before_install:
- openssl aes-256-cbc -K $encrypted_a73b967a7b63_key -iv $encrypted_a73b967a7b63_iv
  -in .httr-oauth.enc -out .httr-oauth -d
env:
  global:
    secure: kl131q0eULfGpJmg4CciT2FI/ofK57tk7nD0oq1zCZmKF04XTYhXjdGWUp/iXdAsOz0tk69ib7JkEvHJcZF3pzremxgmzP03R29a0dEOCTUoKBf5btsq2Q1KLKuL2tbOTxXMudIJVXOMmKAVqrZ6gmNzfcpsE6xjUeOO0s9b2XduHpR6LDH0xd0p3DXBX98RNONPFwLPHGp+8qVxhYWNWhQKZZcAZ2yjXqKtp3Lkn/xd2XytQEtrX9x7Xx2T2kAIonNxyysNzQxbCaYG+57TvLr1RTYmaWcfQhcsoA+7SUgiMTX7nB0DAZ2RLBe/INxToqvp0TXzxOznFf0PU4tRZIex5l2P+FCY+I5ztgPubIggRmSLFDVrSKZLrTU9o9vUFvouW/O5sqMc98MgfLfosHfAeTK3yQAQXb53RZsU6MMKh6LV9i8PTvJg+pLKMCxCmmHM7xXQ3gMzdnDyD7kOp/8U5TzCbRWZEN5p11u+D0U7M0DrWgj9fZLzbVD+XNE4fjlTJT+kIEloy3z7B7z9GwGIEc7kqBR2wznJgBEyX64LIP5IlmPfdPNbzB7qAPhxAw+Fm0gJltLVjblgM3iVyjEP6DciaF2ukrFq8wsXCD52Hlu39gBzTQXh64wPVlhOCJ896fUlV/jqOd6wB29PGF5iTfX6TjIotxfTaMD/6iU=
